# -*- coding: utf-8 -*-
"""GCCA_loss.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fi1qrhXdaUl1q6qB1lea9XpoqZRJwtee

# GCCA Loss Function : To be Implemented
"""

